import React, { useState } from 'react';
import { AgGridColumn, AgGridReact } from 'ag-grid-react';

import 'ag-grid-community/dist/styles/ag-grid.css';
import 'ag-grid-community/dist/styles/ag-theme-alpine.css';
import './App.css';
import Navbar from 'react-bootstrap/Navbar';
import Button from  'react-bootstrap/Button'
import Form from  'react-bootstrap/Form'
import FormControl from  'react-bootstrap/FormControl'
import Nav from  'react-bootstrap/Nav'
import 'bootstrap/dist/css/bootstrap.min.css';
import mainLogo from'./mshistory.png';
import booklogo from'./logobook.png';

import {  Map, Marker, Popup, TileLayer } from "react-leaflet";
import { Icon } from "leaflet";
import * as locationData from './data/coordinates.json';


const App = () => {
    const [gridApi, setGridApi] = useState(null);
    const [gridColumnApi, setGridColumnApi] = useState(null);

    const [rowData, setRowData] = useState([
      {
        "Autor*in": "Abaga, Rosa|Alijevic, Seljan|Arifaj, Ardiana|u.a. (22 Verf.)",
        "Titel": "„Ich dachte ganz Europa spricht Englisch…“ Menschen wandern aus – warum?. Jugendliche Migranten auf den Spuren ihrer Auswanderungsgeschichte",
        "Beitragsart": "Textbeitrag",
        "Umfang": "97 S.",
        "Arbeitsbericht": " ",
        "Jahrgangsstufe": "Jahrgangsstufe 8",
        "Schule": "Geistschule",
        "Einzelbeitrag oder Gruppenbeitrag": "Gruppenbeitrag",
        "Schulart": "Hauptschule",
        "Tutor*in (ID)": "E2A287D70593A7D9ACEBCBB9838AEC",
        "Tutor*innenbericht": "",
        "Regest": "Die Achtklässler sind Schüler einer Vorbereitungsklasse, die zugezogenen ausländischen Schülern und Schülerinnen zu Beginn ihrer Zeit im neuen Land auf den zukünftigen Besuch einer Regelschule vorbereitet. Die Verfasser thematisieren in ihrer Arbeit die unterschiedlichen Migrationserfahrungen ihrer eigenen Familien und dokumentieren diese über drei Generationen. Zu Beginn der Arbeit erstellten die Schüler eine selbst gezeichnete Weltkarte, auf der die Herkunftsländer und Migrationswege der Familien eingezeichnet sind. Die Familien stammen beispielsweise aus dem Balkangebiet, Vorderasien, Afrika oder Amerika. Zusätzlich gestalteten die Schüler im Rahmen eines Theaterprojekts auch ein eigenes Stück, das im Dezember 2002 im Theaterpädagogischen Zentrum Münster aufgeführt wurde. Die Arbeit basiert auf zahlreichen Zeitzeug*inneninterviews und eigenen Erfahrungen der beteiligten Schüler, sodass eine vielschichtige und authentische Arbeit über zum Teil sehr unterschiedliche und aufschlussreiche Migrationsgeschichten entstanden ist.",
        "Themenzeitraum von": 1950,
        "Themenzeitraum bis": 2003,
        "Materialgrundlage": "Fachliteratur|Privatdokumente|Zeitungsartikel|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 395",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2002-2003",
        "Ortsregister": "Amerika|Balkangebiet|Afrika|Vorderasien",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Weggehen - Ankommen. Migration in der Geschichte"
      },
      {
        "Autor*in": "Ackermann, Vera|Al-Barim, Nida|Berjamniski, Olga|u.a. (7 Verf.)",
        "Titel": "Russland in Deutschland?!",
        "Beitragsart": "Textbeitrag",
        "Umfang": "32 S.",
        "Arbeitsbericht": "8 S.",
        "Jahrgangsstufe": "",
        "Schule": "Geschwister-Scholl-Gymnasium|Paul-Gerhardt-Realschule|Waldschule Kinderhaus",
        "Einzelbeitrag oder Gruppenbeitrag": "Gruppenbeitrag",
        "Schulart": "Hauptschule|Gymnasium|Realschule",
        "Tutor*in (ID)": "588B07B8DCAF07B4ACB3E1826157BA",
        "Tutor*innenbericht": "",
        "Regest": "Die Schülerinnen und Schüler, eine gemischte Gruppe von verschiedenen Schulen in Münster, beschäftigen sich mit der Migration von Russland nach Deutschland und legen hierbei den Schwerpunkt auf die Spätaussiedler. In ihrer Arbeit wollen sie herausfinden, welche Erfahrungen die Spätaussiedler in der Vergangenheit gemacht haben, wie sie aufgewachsen sind und welche Gründe es für sie gab, ihre russische Heimat zu verlassen. Grundlage der Arbeit bilden Befragungen in Münster, u.a. in einem russischen Supermarkt in Senden. Bei ihren Umfragen unterscheiden die Verfasser zwischen verschiedenen Generationen der Einwanderer und verdeutlichen die zum Teil sehr unterschiedlichen Einstellungen und Erfahrungen.",
        "Themenzeitraum von": 1763,
        "Themenzeitraum bis": 2003,
        "Materialgrundlage": "Fachliteratur|Privatdokumente|Umfragen|Zeitungsartikel",
        "Signatur im Stadtarchiv": "4 SAB 413",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2002-2003",
        "Ortsregister": "Russland|Senden",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Weggehen - Ankommen. Migration in der Geschichte|Weggehen - Ankommen. Migration in der Geschichte"
      },
      
      {
        "Autor*in": "Falke, Anna",
        "Titel": "Der Wolbecker Tiergarten – ein Stück lebendige Geschichte",
        "Beitragsart": "Textbeitrag",
        "Umfang": "23 S.",
        "Arbeitsbericht": "3 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 11",
        "Schule": "Wilhelm-Hittorf-Gymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "BE856E8D9500CE157E8F3DC442D90D",
        "Tutor*innenbericht": "",
        "Regest": "Der vorliegende Beitrag befasst sich mit der Geschichte des Wolbecker Tiergartens. Dabei greift die Autorin anhand von Fachliteratur in dessen Geschichte bis zu seiner Entstehung Anfang des 18. Jahrhunderts als Jagdressort des damaligen Münsteraner Fürstbischofs Clemens August von Bayern zurück. An dieses ursprüngliche Jagdgebiet erinnern heute nur noch wenige Überreste; der Wald ist vielmehr eher arm an klassischem Jagd-Wild, sondern vor allem gut gepflegtes Naturschutzgebiet, wie Falke in ihrer Bestandsaufnahme des gegenwärtigen Zustands anführt. ",
        "Themenzeitraum von": 1719,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Archivalien|Fachliteratur|Privatdokumente",
        "Signatur im Stadtarchiv": "4 SAB 318",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "Wolbeck",
        "Personenregister": "Clemens August von Bayern",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Falke, Sebastian",
        "Titel": "Kleinzirkusse: Überlebenskampf für Mensch und Tier im Wandel der Zeit",
        "Beitragsart": "Textbeitrag",
        "Umfang": "20 S.",
        "Arbeitsbericht": " ",
        "Jahrgangsstufe": "Jahrgangsstufe 7",
        "Schule": "Wilhelm-Hittorf-Gymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "145EB2EAD9B0949A417A08B6055824",
        "Tutor*innenbericht": "",
        "Regest": "Der Beitrag behandelt das enge Zusammenleben von Mensch und Tier im Zirkus. Der Schüler hat zwei Zirkusfamilien besucht, stellt diese genauer vor und geht auf ihre Lebensbedingungen ein. Der Zirkus „Mulan“ besteht aus einer Mutter mit fünf Kindern sowie einigen Tieren. Zum Zirkus „Corado“ gehören zwei Familien mit ihren Tieren. Der Schüler stellt fest, dass das Leben im Zirkus früher einfacher war, da es heute viel mehr Spektakel und Attraktionen bedarf, um Besucher zu begeistern. Er resümiert, dass die Zeit im Zirkus „stehen geblieben“ sei, da Mensch und Tier hier noch immer auf sehr engem Raum zusammenleben. ",
        "Themenzeitraum von": 1900,
        "Themenzeitraum bis": 1999,
        "Materialgrundlage": "Fachliteratur|Druckschriften|Privatdokumente|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 310",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Fehmer, Farina",
        "Titel": "Ochs und Pferd am Ludgeriplatz – Ein Denkmal auf Wanderschaft",
        "Beitragsart": "Textbeitrag",
        "Umfang": "21 S.",
        "Arbeitsbericht": "2 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 7",
        "Schule": "Wilhelm-Hittorf-Gymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "BE856E8D9500CE157E8F3DC442D90D",
        "Tutor*innenbericht": "",
        "Regest": "1908 begann der Bildhauer Karl Hans Bernewitz an der Tierplastik „Magd mit Ochsen und Knecht mit Pferd“ zu arbeiten. Als er 1912 fertig war, schenkte er es Dr. Konrad von Studt, Ehrenbürger Münsters und ehemaliger Oberpräsident der Provinz Westfalen. Die Statue sollte die Beziehung der westfälischen Stadt zu ihrem sehr ländlichen Umland symbolisieren – ein Umstand der nach Aussage der Autorin jedoch nicht allen Münsteranerinnen und Münsteranern klar war. Zu mehr Bekanntheit hingegen ist die Debatte um die Platzierung des Denkmals gelangt – einerseits aufgrund der hohen Kosten dieses Vorgangs, andererseits aufgrund der häufigen Umstellungen, zuletzt anlässlich der Skulpturenausstellung 1987. Ehemals hinter dem Stadthaus versteckt, wurden sie nun auf den Ludgeriplatz gestellt, wo sie sich – entgegen der Bestrebungen von CDU und FDP – auf Wunsch vieler Münsteranerinnen und Münsteraner hin bis in die Gegenwart befindet. ",
        "Themenzeitraum von": 1908,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Archivalien|Druckschriften|Fachliteratur|Privatdokumente|Zeitungsartikel|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 322",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "Ludgeriplatz|Skulpturprojekte",
        "Personenregister": "Studt, Konrad von|Bernewitz, Karl Hans",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Freitag, Dagmar|Fritsche, Malte|Kuhr, Maximilian|u.a. (5 Verf.)",
        "Titel": "Ich möchte etwas, was du hast. Zum Verhältnis von Bienen und Menschen",
        "Beitragsart": "Textbeitrag",
        "Umfang": "24 S.",
        "Arbeitsbericht": "2 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 7",
        "Schule": "Ratsgymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Gruppenbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "064FD4679C35CEA47A121BDC8B14EF",
        "Tutor*innenbericht": "",
        "Regest": "In ihrem Beitrag behandeln die Schülerinnen und Schüler das Verhältnis zwischen Menschen und Bienen in diachroner Perspektive. Sie gehen auf die Bienenzucht in Frühgeschichte und Antike, die Nutzung der Bienen in Mittelalter und Früher Neuzeit und die Entwicklung der Biene zur „nationalen Angelegenheit“ im 19. und 20. Jahrhundert ein. Sie stellen dabei heraus, dass die Biene zunächst hauptsächlich Nutztier und Honiglieferant war, die heimische Honig- und Wachsproduktion spätestens seit dem Beginn des 20. Jahrhunderts auch Politikum geworden ist: so versuchte man mittels von Schutzerlassen die heimische Bienenzucht zu schützen und anzukurbeln. Während des Nationalsozialismus wurde der Beruf des Imkers propagandistisch aufgeladen. Für ihren Beitrag haben die Verfasser einige Zeitzeug*inneninterviews geführt und sprechen auch die Abbildung eines Bienenkorbs im Tafelwerk des Münsterschen Friedenssaales an.",
        "Themenzeitraum von": -6500,
        "Themenzeitraum bis": 1999,
        "Materialgrundlage": "Archivalien|Fachliteratur|Zeitungsartikel|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 286",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "Rathaus",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Frisch, Barbara|Kühle, Grit|Sternberg, Lioba",
        "Titel": "Ausgebildet für den Tod? Die Pferde der Wehrkreis-, Reit- und Fahrschule VI in Warendorf während des 2. Weltkriegs",
        "Beitragsart": "Textbeitrag",
        "Umfang": "52 S.",
        "Arbeitsbericht": "2 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 9",
        "Schule": "Marienschule",
        "Einzelbeitrag oder Gruppenbeitrag": "Gruppenbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "B0D1A952C83F620E206C2FD888C830",
        "Tutor*innenbericht": "",
        "Regest": "Die Schülerinnen gehen der Frage nach, ob die Pferde der Reit- und Fahrschule in Warendorf während des Zweiten Weltkriegs lediglich für den Kampf – und somit häufig den Tod – ausgebildet wurden oder ob diese „treue Kameraden“ der Soldaten waren. Hierfür haben die Schülerinnen mehrere Zeitzeug*inneninterviews geführt, die sie im Anhang ausführlich dokumentieren. Von ihren Interviewpartnern haben sie auch viele zeitgenössische Fotografien erhalten, die sie in ihre Arbeit integrieren. Ab Herbst 1940 befand sich die Wehrkreis-, Reit- und Fahrschule in Warendorf und hatte einen Bestand von etwa 450 Pferden. Die Tiere, Remonten genannt, wurden hier ausgebildet und dann an verschiedene Truppen weitergegeben. Die Schülerinnen arbeiten heraus, dass die Pferde häufig als erste während des Kampfes getroffen wurden, da ihr Einsatz vor dem Hintergrund des Krieges mit schweren Feuerwaffen und Panzern eigentlich nicht mehr zeitgemäß war. Zudem war das Mitführen und Versorgen der Pferde an der Front äußerst kompliziert. Ihre zu Beginn gestellten Forschungsfragen können sie abschließend nur bejahen. ",
        "Themenzeitraum von": 1933,
        "Themenzeitraum bis": 1945,
        "Materialgrundlage": "Archivalien|Fachliteratur|Privatdokumente|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 313",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "Warendorf",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Frisch, Beate|Ueing, Sabrina|Wessels, Juliane|u.a. (4 Verf.)",
        "Titel": "Der Bischof und sein Wild. Der Tiergarten in Wolbeck als Jagdrevier der Münsterischen Fürstbischöfe",
        "Beitragsart": "Textbeitrag",
        "Umfang": "54 S.",
        "Arbeitsbericht": "3 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 8",
        "Schule": "Marienschule",
        "Einzelbeitrag oder Gruppenbeitrag": "Gruppenbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "B0D1A952C83F620E206C2FD888C830",
        "Tutor*innenbericht": "",
        "Regest": " „Der Bischof und sein Wild“, eine Titelgebung in Anlehnung an die TV-Serie „Der Doktor und das liebe Vieh“, geht der Frage nach, warum und wie die Münsteraner Fürstbischöfe im Tiergarten Wobeck gejagt haben. Wozu braucht ein Bischof überhaupt ein Jagdrevier? Mit ihrem Beitrag stellen die Schülerinnen die Entwicklung eines Tiergeheges dar, das ursprünglich der Befriedigung der Jagdlust und herrschaftlichen Repräsentation diente und heute ein Naherholungsgebiet ist. Die Grundlage der Arbeit bildet die lokalhistorische Literatur, die ergänzt wird mit archivalischen Quellen zur Anlage des Tiergartens, zur Züchtung und Pflege des Wildbestandes und zur Jagd selber und ihrer herrschaftlichen Funktion. Die Arbeit gliedert sich in einen Abschnitt zu Hintergrundinformationen, einer Vertiefung und Präzisierung und einer abschließenden Bewertung. Nebenaspekte wie z.B. die Waldnutzung werden zwar gestreift, von der eigentlichen Fragestellung wird jedoch nicht abgewichen. Zunächst einmal wird von den Verf. die Parkanlage in ihrer Entstehung beschrieben und mittels Fotos und Kartenbeilagen ein Eindruck der Anlage vermittelt. Aus der Anlage des Parks erschließen sie die vermutliche Organisationsform der Jagd: der Parforcejagd. Sie befragen Experten und wenden sich auch an den Bischof, der ihnen knapp erklärt, dass seine Vorgänger mehr weltliche als geistliche Herren waren und dass er selbst nicht jagen würde. In der Bewertung kommen die Schülerinnen zu einer Stellungnahme „zum Umgang der Fürstbischöfe mit ihrem Wild“ (S. 13 ff.). Sie meinen, dass es damals noch keine ökologischen Probleme gegeben haben mag, finden die Jagdmethode unfair und freuen sich über die spätere Umgestaltung der Anlage in einen Tiergarten: „Am Ende ist die Geschichte für das Wild also doch noch zu einem guten Ende gekommen.“ (S. 14) Ein Kochrezept sowie ausgewählte Quellen sind im Anhang der Arbeit zu finden.",
        "Themenzeitraum von": 1537,
        "Themenzeitraum bis": 1819,
        "Materialgrundlage": "Archivalien|Expert*inneninterviews|Fachliteratur|Zeitungsartikel",
        "Signatur im Stadtarchiv": "4 SAB 314",
        "Auszeichnungen": "4. Bundespreis",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "Wolbeck",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Frye, Annika|Janßen, Kerstin|Knüpper, Vanessa",
        "Titel": "Von der Vie-h-lfalt zur Schw-einfalt. Und natürlich auch zur Rindf-falt, Reinfalt, Rindeinfalt…ehm…oder so!",
        "Beitragsart": "Textbeitrag",
        "Umfang": "37 S.",
        "Arbeitsbericht": "5 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 10",
        "Schule": "Marienschule",
        "Einzelbeitrag oder Gruppenbeitrag": "Gruppenbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "FC97EEF30DCA26FF770C4AE5D0F506",
        "Tutor*innenbericht": "",
        "Regest": "Vor allem ausgehend von Erzählungen aus ihrer Großelterngeneration und Interviews mit diesen betrachten die Verfasserinnen die strukturellen Veränderungen der Landwirtschaft vor und nach dem Zweiten Weltkrieg. Eingebettet in eine Überblicksskizze der Landwirtschaftsgeschichte werden in erster Linie Schweine- und Rinderzucht genauer unter die Lupe genommen. Dabei fällt auf, dass die Bauernhöfe sich weg vom vielfältigen, breit aufgestellten Idealbild, dass sich viele vom Landleben machen, hin zu einem hochspezialisierten Glied der industriellen Fertigungsketten entwickelt haben. Ernteerträge sind massiv angestiegen, Tiere werden eng zusammengetrieben, Züchtungen auf Erträge hin optimiert. Die kleineren Betriebe wurden in den 60er und 70er Jahren von den großen Mastbetrieben verdrängt, die Beziehung zwischen Mensch und Tier weniger innig. Episoden wie die Verunsicherung während des BSE-Skandals zeigen nach Ansicht der Autoren jedoch auch für die Verbraucher die Schattenseiten dieser Entwicklung sehr deutlich auf. ",
        "Themenzeitraum von": 1930,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Archivalien|Fachliteratur|Internetquellen|Privatdokumente|Zeitungsartikel|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 332",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Göhler, Anna-Katharina",
        "Titel": "Der Tasmanische Tiger. Eine lebendige Vergangenheit",
        "Beitragsart": "Textbeitrag",
        "Umfang": "56 S.",
        "Arbeitsbericht": "2 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 11",
        "Schule": "Schillergymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "594B52518CF9DC6A597F275C7BC28E",
        "Tutor*innenbericht": "",
        "Regest": "Da sich die Schülerin während des Wettbewerbszeitraumes in Tasmanien befand, hat sie sich mit der Geschichte des Tasmanischen Tigers auseinandergesetzt. Dieser gilt seit längerer Zeit als ausgestorben, was insbesondere durch die Entdeckung Tasmaniens durch Europäer ausgelöst wurde. Ab dem Beginn des 19. Jahrhunderts wurde vermehrt zur Tötung des Tasmanischen Tigers aufgerufen, da dieser Vieherden angriff. Mit der Einführung von Jagdprämien wurde die langsame Ausrottung des Tigers in Kauf genommen. Die Schülerin zeichnet die Entdeckung des Tieres durch die Europäer und seine langsame Vernichtung detailliert nach. Zudem geht sie auf den Tasmanischen Tiger in Zoos und Tierparks ein. Abschließend diskutiert sie, ob der Tiger vollständig ausgerottet ist und wie seine „Zukunft“ aussehen könnte – seit längerer Zeit wird über die Möglichkeit, den Tasmanischen Tiger zu klonen, diskutiert. ",
        "Themenzeitraum von": 1800,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Fachliteratur|Filme|Internetquellen|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 307",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Glück, Ivo|Glück, Nils Ole",
        "Titel": "Alles dreht sich um die Tiere – Tierhaltung auf einem Hof im Oberbergischen Land",
        "Beitragsart": "Textbeitrag",
        "Umfang": "121 S.",
        "Arbeitsbericht": "4 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 7",
        "Schule": "Wilhelm-Hittorf-Gymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Gruppenbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "BE856E8D9500CE157E8F3DC442D90D",
        "Tutor*innenbericht": "",
        "Regest": "Diese Arbeit, die den Wandel der Tierhaltung auf dem großelterlichen Hof über drei Generationen zurückverfolgt, nutzt insbesondere Interviews und private Materialien aus dem Familienkreis als Informationsquelle. Am Wandel der Tierhaltung wird das Wechselverhältnis von betriebswirtschaftlichen Erfordernissen und dem Arbeitsalltag des Familienbetriebes erläutert und so zugleich eine Familiengeschichte geschrieben, die dem Großvater zum 73. Geburtstag gewidmet ist. In Wort und Bild wird das Verhältnis von Mensch und Tier im Wandel der Zeit am Beispiel des großelterlichen Hofes sehr gut und auf hohem Reflexionsniveau dokumentiert. Im Hauptteil (S. 6-79) wird zunächst der Hof Simon in seinem heutigen Bestand dargestellt und die Geschichte von Hof und Familie erzählt (S. 6-9). Im zentralen Untersuchungsabschnitt wird für fünf Zeiträume, orientiert am Zweiten Weltkrieg und dem Generationswechsel auf dem Hof (bis 1939, 1939-1945, 1945-1952, 1953-1993 und danach), untersucht, welche Tiere gehalten wurden, wie diese versorgt wurden und welchen Nutzen man von ihnen hatte (S. 10-72). Nachdem zunächst die konkrete Ebene des sich wandelnden Verhältnisses zwischen Mensch und Tier in den täglichen Arbeitsabläufen gezeigt wird, kommen die Ergebnisse zur systematischen Auswertung („Ergebnisauswertung / Vergleich der Zeitabschnitte“, S. 73-79). Hier präsentieren die Autoren ihre empirischen Ergebnisse zunächst in einer farbigen Verlaufstabelle der Tierhaltung (S. 73), arbeiten Unterschiede insbesondere der markt- und technikangepassten Veränderungen heraus, betonen aber, dass durchgängig durch die Generationen eine Einstellung vorherrschte, die mit einem Zitat beschrieben wird: „Ein verhätscheltes Tier gibt es ... nicht auf einem Hof. Da weißt du schon, wenn das Kälbchen geboren wird: ‚Du wirst in ein paar Jahren geschlachtet. Du bist dafür geboren - um den Betrieb zu erhalten.‘“ Sie vermerken aber: „Trotz dieser Rolle der Tiere ist der Umgang mit ihnen nach unserer Beobachtung ruhig, freundlich und nicht aggressiv.“ Die Geschwister arbeiten so heraus, dass die Landwirte möglicherweise einen weitaus reflektierteren Umgang mit dem Tier üben als mancher wohlmeinende Haustierhalter (S. 78 f.). „Als Bauer muss man die Tiere mögen. Wenn dir Tiere eine Last sind, dann wirst du besser nie Bauer“, zitieren sie ihren Großvater. Der Beitrag fällt durch seine beinahe professionelle Gestaltung auf. Sein klar gegliedertes und mit zahlreichen aussagekräftigen und gut eingebauten Fotos aus Privatbesitz angereichertes Äußeres und das gute Gespür für die Auswahl von Interviewpassagen in der Darstellung sind hervorzuheben. Gerade in dieser Technik dringen sie tief ins historische Mensch-Tier-Verhältnis ein.",
        "Themenzeitraum von": 1930,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Archivalien|Fachliteratur|Expert*inneninterviews|Privatdokumente|Zeitungsartikel|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 299",
        "Auszeichnungen": "3. Bundespreis",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Grevenbrock, Kerstin|Mayer, Rike",
        "Titel": "Münsterische Stadtgeschichte im Tierbildsymbol",
        "Beitragsart": "Textbeitrag",
        "Umfang": "29 S.",
        "Arbeitsbericht": "2 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 8",
        "Schule": "Marienschule",
        "Einzelbeitrag oder Gruppenbeitrag": "Gruppenbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "5B1712DC2A7A6732320CCAED841A2D",
        "Tutor*innenbericht": "",
        "Regest": "Anhand der auf den bronzenen Handläufen am Haupteingang des Stadthauses an der Clemensstraße abgebildeten Tiere beleuchten die Schülerinnen die Stadtgeschichte Münsters. Die von dem Künstler Rudolf Breilmann 1960 zum Neubau des Stadthauses gefertigten Türgriffe bilden eine Kuh, einen Hahn, Fische, Gänse, eine Friedenstaube, eine Ziege und ein Pferd ab. Die Schülerinnen arbeiten heraus, dass die Kuh für das Kuhviertel Münsters steht und dass der Hahn auf eine Sage über die Rettung der Stadt durch einen Hahnenschrei verweist. Die Fische stehen für den Alten Fischmarkt, während die Gänse das Symbol für den Heiligen Liudger sind, den ersten Bischof Münsters. Die Taube als Symbol des Westfälischen Friedens befindet sich neben der Ziege, die an den „Ziegenbaron“ erinnert – einen großen Förderer der Ziegenzucht im Münsterland um 1900. Das Pferd steht für die Pferdegasse, wo sich früher die bischöflichen Reitställe befanden. ",
        "Themenzeitraum von": 1960,
        "Themenzeitraum bis": 1960,
        "Materialgrundlage": "Fachliteratur|Zeitungsartikel|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 300",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "Kuhviertel",
        "Personenregister": "Heilige Liudger",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Hakenes, Theresa",
        "Titel": "Delphine. Attraktion, Therapeuten, Opfer",
        "Beitragsart": "Textbeitrag",
        "Umfang": "66 S.",
        "Arbeitsbericht": "3 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 8",
        "Schule": "Kardinal-von-Galen-Gymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "7A4E717D0A1A134EF5711A14906A72",
        "Tutor*innenbericht": "",
        "Regest": "In ihrem Beitrag beschäftigt sich die Schülerin mit verschiedenen Aspekten des Verhältnisses zwischen Delphinen und Menschen. Zunächst geht sie auf die Bedeutung des Delphins in der Antike, das Tier als Symbol im Christentum und den Delphin in Film und Literatur ein. Dann beschreibt sie die Geschichte des Delphinariums im Allwetterzoo Münster, das 1974 eröffnet wurde. Dieses war zwar bei vielen Zoobesuchern beliebt, stand aber bei Tierschützern aufgrund der stattfindenden Delphinshows häufiger in der Kritik. Die Schülerin behandelt auch das Verhältnis zwischen Pflegern, Trainern und Tieren und beschreibt einige Versuche, in Münster eine Delphintherapie für Kinder mit Behinderungen durchzuführen. Abschließend folgen Kapitel zur Delphintherapie und der Gefährdung von Delphinen durch Fischerei.",
        "Themenzeitraum von": 1900,
        "Themenzeitraum bis": 1999,
        "Materialgrundlage": "Fachliteratur|Internetquellen|Zeitungsartikel",
        "Signatur im Stadtarchiv": "4 SAB 303",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "Zoo",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Hasgül, Eda|Ohms, Miriam|Scharnowski, Ruth",
        "Titel": "Der alte August – Elefant im Zoo. Oder: Wer den Zoo kennt, kennt auch Fräulein August",
        "Beitragsart": "Textbeitrag",
        "Umfang": "63 S.",
        "Arbeitsbericht": "2 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 5",
        "Schule": "Marienschule",
        "Einzelbeitrag oder Gruppenbeitrag": "Gruppenbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "5B1712DC2A7A6732320CCAED841A2D",
        "Tutor*innenbericht": "",
        "Regest": "Der Beitrag beschäftigt sich mit der Elefantenkuh „August“, die in den Jahren von 1950 bis 1994 im Münsteraner Zoo lebte und stattliche 49 Jahre alt geworden ist. Nach und vor ihr erhielten weitere Elefanten im Zoo diesen Namen. Die Arbeit untersucht das Verhältnis dieser Tiere zu den Menschen und umgekehrt. Im Zooarchiv konnten Presseberichte ausgewertet und Zoobesucher und Tierpfleger zu den Tieren befragt werden. Die Schülerinnen erzählen die Geschichte der „August“-Elefanten als Zoogeschichte. Im Abschnitt über die Geschichte des Zoos sticht die Passage über den Zoo in den Kriegs- und Nachkriegsjahren heraus. (S. 12-15). Die Verf. gehen auch auf einen veröffentlichten Erinnerungsbericht eines französischen Kriegsgefangenen ein, der im Zoo arbeitete. Der Münsteraner Zoo musste 1945 seine Elefanten an den Zoo in Antwerpen als Reparationsleistung abtreten. Hierzu präsentieren sie die Regierungsanordnung vom 11.7.1945 als Quelle. Im Jahre 1950 kam der erste Nachkriegs-„August“, eine Elefantenkuh aus Ceylon, in den Münsteraner Zoo. Heute tragen die „August“-Nachfolger auch einmal den Namen „Fräulein August“. Nach der Vorstellung der Tiere wird versucht, deren Verhältnis zu den Menschen, Pflegern wie Besuchern, zu beschreiben. Sie begründen, warum der „alte August“ so beliebt war: Er, nein: sie, war besonders zutraulich und wurde im Alter weiß (S. 49). Dazu gesellte sich wohl auch der Stolz der Münsteraner Bevölkerung auf den ersten Elefanten in der Nachkriegszeit - wohl verbunden mit dem Gefühl, dass es wieder „aufwärts“ ginge. Eine gelungene Mischung aus selbst verfassten Texten, Materialien und einige ausdrucksstarke Fotos machen die Arbeit anschaulich.*",
        "Themenzeitraum von": 1945,
        "Themenzeitraum bis": 1994,
        "Materialgrundlage": "Archivalien|Druckschriften|Fachliteratur|Zeitungsartikel|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 294",
        "Auszeichnungen": "5. Bundespreis",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "Zoo",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Hoeren, Henrike",
        "Titel": "Der Schlachthof Münster 1885-1999",
        "Beitragsart": "Textbeitrag",
        "Umfang": "9 S.",
        "Arbeitsbericht": "1 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 5",
        "Schule": "Marienschule",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "B0D1A952C83F620E206C2FD888C830",
        "Tutor*innenbericht": "",
        "Regest": "1885 eröffnete der erste Münsteraner Schlachthof. In ihrem Beitrag skizziert die Autorin Geschichte und Entwicklung des ungeliebten Gebäudes, das sowohl von Anwohnerinnen und Anwohnern als auch offiziellen Stellen immer wieder kritisiert wurde. Der Schlachthof, der zu Beginn der 1970er Jahre seine größte Auslastung erreichte, musste 1999, als der Pachtvertrag auslief, sowohl aufgrund anhaltender Beschwerden aus der Nachbarschaft als auch angesichts Schulden bei der Stadt Münster seine Pforten schließen. Neben dieser Darstellung wirft die Autorin auch einen kritischen Blick auf einen von industriellen Maßstäben und Bedingungen geprägten Umgang mit Tieren und Fleisch. ",
        "Themenzeitraum von": 1882,
        "Themenzeitraum bis": 1999,
        "Materialgrundlage": "Archivalien|Fachliteratur|Internetquellen|Zeitungsartikel",
        "Signatur im Stadtarchiv": "4 SAB 323",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Hutten, Verena|Pierchalla, Greta|Riedel, Christine",
        "Titel": "Alle „Feriengäste“ sind „so gut wie stubenrein“. Aprilscherze, Anteilnahme, unerfüllte Wünsche – Das Verhältnis der Münsteraner zu ihren Zootieren",
        "Beitragsart": "Textbeitrag",
        "Umfang": "65 S.",
        "Arbeitsbericht": "4 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 7",
        "Schule": "Kardinal-von-Galen-Gymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Gruppenbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "7A4E717D0A1A134EF5711A14906A72",
        "Tutor*innenbericht": "",
        "Regest": "Der Beitrag beschäftigt sich mit dem Aprilscherz einer Münsteraner Zeitung, der im Kontext des bevorstehenden Umzugs des Zoos zur vorübergehenden privaten Unterbringung der Tiere aufrief. Ausgangspunkt für die Recherche zum Wettbewerbsbeitrag war die Großmutter einer Schülerin, von der damals die Idee zum Aprilscherz stammte. Die Schülerinnen interviewten damals Beteiligte, führten eine Befragung durch und gingen dem Presserummel nach. Nachdem zunächst die Geschichte des Münsteraner Zoos und seiner Neubauplanung vorgestellt wird („2. Wohin mit dem Zoo“, S. 2-11), steht der Aprilscherz im 3. Kapitel im Mittelpunkt (S. 12-24). Im Jahre 1971 wurde zum 1. April in den „Westfälischen Nachrichten“ ein Artikel veröffentlicht, in dem gefragt wurde, wer Zootiere für eine längere Zeit bei sich aufnehmen kann, zumindest so lange, bis der neue Zoo fertig gestellt ist (Baubeginn war 1969). Die Schülerinnen schildern auf lebendige und amüsante Weise die Reaktion der Bevölkerung und den wahren Ansturm auf den Zoo. Aus der Befragung und aus der Presseauswertung werden die unterschiedlichen Motive deutlich, aus denen Kinder wie Erwachsene Zootiere aufnehmen würden. Haupttenor der Antworten war dabei: Wer von uns hätte nicht gerne einen Affen als Haustier? Im 4. Kapitel geht es um die aktuelle Dimension des Themas. Unter der Überschrift „Würde ein solcher Aprilscherz heute auch so viele Leute ansprechen?“ (S. 25-32) werten die Verf. eine Passantenbefragung aus. Bei einer weiterhin bestehenden Bereitschaft zur Mithilfe, welche die Schülerinnen konstatieren, deutet sich aber auch an, dass die Wahrnehmung von Presseinformationen heute nicht mehr mit der im Jahre 1971 identisch ist. Der Arbeit gelingt es, die Verbundenheit der Münsteraner mit ihrem Zoo aufzuzeigen. Die Dokumentation des Presserummels (S. 37-59) liest sich mit großem Vergnügen.",
        "Themenzeitraum von": 1967,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Fachliteratur|Umfragen|Zeitungsartikel|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 305",
        "Auszeichnungen": "4. Bundespreis",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "Zoo",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Janotta, Anna Maren",
        "Titel": "Schweinereien. Die Beziehung zwischen Mensch und Schwein in unserer Geschichte",
        "Beitragsart": "Textbeitrag",
        "Umfang": "26 S.",
        "Arbeitsbericht": "3 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 6",
        "Schule": "Marienschule",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "B0D1A952C83F620E206C2FD888C830",
        "Tutor*innenbericht": "",
        "Regest": "In ihrer Arbeit setzt sich die Verfasserin mit dem Verhältnis zwischen Menschen und Schweinen auseinander. Zwischen den Polen des Nutzens des Schwein für den Menschen („Schwein gehabt“) und der Ausnutzung des Schweins durch den Menschen („Du armes Schwein!“) reflektiert sie das Zusammenleben von Mensch und Schwein, insbesondere in ländlichen Bereichen wie dem Münsterland. Durch seine geringen Ansprüche und seine weite Verbreitung diente das Schwein dem Menschen schon immer, besonders in Krisenzeiten, als wichtige Nahrungsquelle. Nach Auswertung der Verfasserin jedoch habe diese Nutzung nun inflationär stattgefunden: Um billigen Fleischkonsum zum Teil des Alltags zu machen, hätten sich die Bedingungen der Schweinehaltung rapide verschlechtert und industriellen Maßstäben angepasst. Die daraus auch für den Menschen resultierenden Konsequenzen wie die Übertragung von Krankheiten durch Fleischverzehr erscheinen der Autorin in ihrem abschließenden Statement als legitimes Signal, um den Umgang mit diesen Nutztieren dringend tierfreundlicher zu gestalten. ",
        "Themenzeitraum von": 1900,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Druckschriften|Fachliteratur|Umfragen|Zeitungsartikel",
        "Signatur im Stadtarchiv": "4 SAB 320",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Kühne, Alexander",
        "Titel": "Tiere in unserem Leben: Die Haltung von Haustieren in unserer Familie in Rußland und in Kasachstan!",
        "Beitragsart": "Textbeitrag",
        "Umfang": "16 S.",
        "Arbeitsbericht": "1 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 7",
        "Schule": "Wilhelm-Hittorf-Gymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "145EB2EAD9B0949A417A08B6055824",
        "Tutor*innenbericht": "",
        "Regest": "In seinem Beitrag arbeitet der Schüler die Geschichte seiner Familie ab 1917 auf. Auf der Grundlage von Interviews mit Verwandten beschreibt er das Leben seiner Großmutter in der Ukraine von 1917 bis 1958, die dort Land und viele Tiere besaß. Ab 1924 wurde der Hof unter Stalin in eine Kolchose umgewandelt und fast der gesamte Besitz musste abgegeben werden. Mit Ausbruch des Zweiten Weltkriegs siedelte die Familie nach Bagan über und baute sich dort erneut eine Landwirtschaft auf. Die Eltern des Verfassers zogen 1978 nach Alma-Ata in Kasachstan, wo sie nur wenige Tiere hielten, die sie selbst schlachteten. Die Familie zog 1996 schließlich nach Münster, verkaufte alle Tiere und ihr Haus.",
        "Themenzeitraum von": 1917,
        "Themenzeitraum bis": 1996,
        "Materialgrundlage": "Privatdokumente|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 289",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Köppen, Lukas",
        "Titel": "Unsichtbar mitten unter uns: Die Verlagerung des Lebensraumes wilder Tiere in die Stadt Münster",
        "Beitragsart": "Textbeitrag",
        "Umfang": "14 S.",
        "Arbeitsbericht": "1 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 7",
        "Schule": "Wilhelm-Hittorf-Gymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "145EB2EAD9B0949A417A08B6055824",
        "Tutor*innenbericht": "",
        "Regest": "In seinem Beitrag geht der Schüler auf Tiere ein, deren Lebensraum eigentlich nicht die Stadt ist, die man aber dennoch innerhalb des Stadtgebiets finden kann. Darunter fallen beispielsweise Waschbären oder Fledermäuse. Kurz wird auch die steigende Population von Wildschweinen angesprochen, weshalb es häufiger zu Wildunfällen kommt.",
        "Themenzeitraum von": 1900,
        "Themenzeitraum bis": 1999,
        "Materialgrundlage": "Expert*inneninterviews|Fachliteratur|Zeitungsartikel",
        "Signatur im Stadtarchiv": "4 SAB 306",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Krüger, Temba",
        "Titel": "Die älteste Sauerei Deutschlands. Was haben denn Tiere mit karnevalfeiernden Schützen zu tun?",
        "Beitragsart": "Textbeitrag",
        "Umfang": "76 S.",
        "Arbeitsbericht": "2 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 10",
        "Schule": "Marienschule",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "FC97EEF30DCA26FF770C4AE5D0F506",
        "Tutor*innenbericht": "",
        "Regest": "Die Schülerin beschäftigt sich mit der „Schweine-Schinken-Schützengesellschaft“, eines 1890 gegründeten Karnevalsvereins aus Münster mit nur 30 Mitgliedern. Sie beschreibt die Bräuche der Gesellschaft, vorkommende Ämter und die festgelegte Rangordnung. Einmal im Jahr feiert der Verein beispielsweise den „Ball der Schweine“, nimmt am Rosenmontagszug teil und veranstaltet ein Schützenfest. Sie hat einige Interviews mit Mitgliedern geführt und integriert viele Fotos von Aktionen der Gesellschaft in ihre Arbeit; außerdem greift sie auf eine Chronik und Presseartikel zurück. ",
        "Themenzeitraum von": 1890,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Archivalien|Druckschriften|Fachliteratur|Zeitungsartikel|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 296",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Krane, André|Peters, Daniel|Windhaus, Sebastian",
        "Titel": "Freibankfleisch. Minderes Fleisch für „mindere“ Menschen?",
        "Beitragsart": "Textbeitrag",
        "Umfang": "45 S.",
        "Arbeitsbericht": "2 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 8|Jahrgangsstufe 10",
        "Schule": "Schillergymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Gruppenbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "594B52518CF9DC6A597F275C7BC28E",
        "Tutor*innenbericht": "",
        "Regest": "„Freibankfleisch“ meinte minderwertiges, oder bedingt taugliches Fleisch, das verbilligt zum Verkauf angeboten wurde. Ein Modell, das seit 1994, auch bedingt durch die ohnehin strittig preiswerte Massentierhaltung, in Deutschland nicht mehr erlaubt ist. In ihrer Arbeit zeigen die Autoren auf, wie dieses – entgegen dem historisch betrachtet stets hoch angesehenen Stellenwert des Luxusguts ‚Fleisch‘ – während des Zweiten Weltkriegs unter anderem an die knapp drei Millionen Kriegsgefangenen und Zwangsarbeiter – auch in Münster – verteilt wurde. Gegenüber der ideologisch als minderwertig betrachteten „slawischen Untermenschen“ bestanden wenig Skrupel, nur fragwürdig genießbares Fleisch zum Teil der ohnehin sehr mangelhaften Ernährung zu machen. Wie die Verfasser jedoch anführen, war der Verzehr von Freibankfleisch in Zeiten extremen Mangels – wie während des Krieges – keine Ausnahmesache und wurde, auch das dokumentieren die Briefe und Unterlagen, die sie in ihre Arbeit einflechten, nach Möglichkeit kontrolliert, sodass gewisse Standards eingehalten werden sollten. ",
        "Themenzeitraum von": 1939,
        "Themenzeitraum bis": 1994,
        "Materialgrundlage": "Archivalien|Druckschriften|Fachliteratur|Expert*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 326",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Kunze, Vera",
        "Titel": "Welche Rolle spielte und spielt der Zierfisch im Leben der Menschen?",
        "Beitragsart": "Textbeitrag",
        "Umfang": "24 S.",
        "Arbeitsbericht": " ",
        "Jahrgangsstufe": "Jahrgangsstufe 6",
        "Schule": "Wilhelm-Hittorf-Gymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "BE856E8D9500CE157E8F3DC442D90D",
        "Tutor*innenbericht": "",
        "Regest": "In ihrem Beitrag geht die Autorin, selbst begeisterte Zierfisch-Züchterin, der Frage nach, welche Rolle Zierfische im Leben von Menschen einnahmen. Möglich wurde der Beginn der modernen Fischzucht erst durch technische Neuerungen zweierlei Natur: Einerseits musste es möglich sein, den Tieren vor Ort ähnliche Lebensumstände wie in ihrer natürlichen Umgebung zu bieten. Davor jedoch musste es für exotischere Exemplare zunächst einmal gelingen, diese auch unbeschadet vor Ort ankommen zu lassen, also zum Züchter zu transportieren, wie die Verfasserin eingangs erläutert. In Münster gründete sich 1908 der Verein für Aquarien- und Terrarienkunde Münster, der zum Zeitpunkt der Arbeit etwa 60 Mitglieder umfasst. Aus diesem rekrutieren sich auch die Interviewpartner, auf die Kunze weite Teile ihrer Arbeit stützt. Anhand von Umfragen erfasst sie Motivation zur Aufnahme sowie zur Beendigung des Hobbys Zierfischhaltung, woran sie eine Typenbildung anschließt. Ob maßgeblich motiviert durch die Freude an den Fischen, dem Vereinsleben oder Zucht- bzw. Händlerinteressen: Nach Einschätzung der Verfasserin vereint die Achtung vor der Natur alle ihre Interviewpartner.",
        "Themenzeitraum von": 1908,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Zeitzeug*inneninterviews|Umfragen|Zeitungsartikel",
        "Signatur im Stadtarchiv": "4 SAB 331",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Kurlemann, Kathrin|Rainer, Miriam",
        "Titel": "Das elefantöse Münster. Von Anfang bis Jetzt",
        "Beitragsart": "Textbeitrag",
        "Umfang": "57 S.",
        "Arbeitsbericht": "1 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 7",
        "Schule": "Wilhelm-Hittorf-Gymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Gruppenbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "BE856E8D9500CE157E8F3DC442D90D",
        "Tutor*innenbericht": "",
        "Regest": "Die Schülerinnen behandeln in ihrem Beitrag die Geschichte der Elefanten im Allwetterzoo Münster. Hierfür haben sie die Elefanten beobachtet, Einblicke in das Zooarchiv erhalten und Gespräche mit Pflegern sowie mit dem Leiter des Zoos, Dr. Jörg Adler, geführt. Der erste Elefant mit dem Namen „August“ kam 1899 nach Münster, 25 Jahre nach der Gründung des Allwetterzoos durch Hermann Landois. Zwar wurde das Gehege der Elefanten während des Zweiten Weltkriegs nicht beschädigt, die beiden dort lebenden Elefantenkühe wurden jedoch 1945 als Reparationsgut nach Antwerpen gebracht. 1950 kam erneut ein Elefant nach Münster, der bis 1994 lebte. Die Schülerinnen gehen insbesondere auf den ersten Elefanten „August“ und die Presseberichterstattung über das Tier ein. Sie beschreiben auch die Haltung sowie Pflege im Zoo und beleuchten weitere Schlaglichte der Geschichte der Elefanten im Zoo, wie die Geburtstage der Tiere, lustige Anekdoten und besondere Aktionen. ",
        "Themenzeitraum von": 1899,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Archivalien|Fachliteratur|Zeitungsartikel|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 287",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "Zoo",
        "Personenregister": "Landois, Hermann",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Lütke, Schelhowe, Theresa",
        "Titel": "Von bekannten Stadthühnern, Kirchturmshähnen und dem gewöhnlichen Federvieh. Zur Geschichte und Bedeutung von Hühnern in Münster und Umgebung",
        "Beitragsart": "Textbeitrag",
        "Umfang": "103 S.",
        "Arbeitsbericht": "4 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 10",
        "Schule": "Annette-von-Droste-Hülshoff-Gymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "5D04BE2DC6F0D2B0DE40C456CE4EE1",
        "Tutor*innenbericht": "",
        "Regest": "Die Autorin gewinnt in dem Beitrag über die Geschichte der Mensch-Huhn-Beziehung am Beispiel der Münsteraner Hühner dem Thema eine Reihe interessanter Sichtweisen ab. Der Fragestellung nach Kontinuität und Wandel in der Mensch-Huhn-Beziehung wird durch die mehrfache Gegenüberstellung historischer und aktueller Aspekte nachgegangen. Die Untersuchung des wirtschaftlichen Nutzens, des Vereinslebens in Geflügelzuchtvereinen und der kulturellen Bedeutung des Huhns erforderte dabei die Heranziehung von Quellen und Hintergrundinformationen höchst unterschiedlicher Provenienz, so von Zeitzeug*inneninterviews, der Lokalpresse, der heimat- und lokalgeschichtlichen Literatur sowie von Vereinsarchivalien. Nach einem Abschnitt über die \"prominenten Hühner Münsters\" (S. 8-21) folgt die Geschichte der Haltung von Hühnern als Nutztiere (\"Wirtschaftshühner\", S. 22-43) und der verschiedenen Haltungsbedingungen in Vergangenheit und Gegenwart. Insbesondere im Abschnitt über die Hühnerzucht in den heutigen Vereinen (S. 44-59) kann die historische Dimension des Themas herausgearbeitet werden, denn bei dem 1996 vollzogenen Zusammenschluss von Geflügelzüchtervereinen zu einem Provinzialverband konnte man auf eine \"aktenkundige\" Geschichte seit 1910 zurückblicken. Gerade dieser Abschnitt über die Entwicklung der Hühnerhaltung und Hühnerzucht in Vereinen stellt das Mensch-Tier-Verhältnis und den Hobby-Aspekt des Tiers in den Mittelpunkt und weist auf die hohe Kontinuität dieser Beziehung hin. Im Abschnitt über \"Die Wächter über der Stadt: Bedeutungsvolle Hähne auf älteren und neueren Kirchtürmen in Münster\" (S. 60-89) zum kulturellen Wert des Huhns navigiert die Verf. durch eine Reihe teils widersprüchlicher Informationen und belegt, dass ein Großteil der Münsteraner Kirchen erst in der jüngeren Vergangenheit ihre Kirchturmshähne erhielt. Auch diese Tradition, die ein Tier in den Mittelpunkt stellt, erweist sich somit als neueren Datums. In ihrer Schlussbeurteilung (S. 90-93) resümiert die Verf., dass das Huhn heute zumeist aus den Haushalten der Stadt verschwunden ist: Das Huhn in der Legebatterie hat das Haushuhn abgelöst. Der Hahn wiederum steht in Münster als \"Symbol für Freiheit und Frieden\". Durch eine Reihe humoristisch-kritischer Einfügungen und liebevoller Darstellungen drückt sich aus, dass die Verf. ihre \"Liebe\" zu den Hühnern entdeckt hat (S. 92).",
        "Themenzeitraum von": 1910,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Archivalien|Druckschriften|Fachliteratur|Zeitungsartikel|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 317",
        "Auszeichnungen": "2. Bundespreis",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Marguc, Sarah",
        "Titel": "Die Entwicklung des Tierschutzgedankens am Beispiel des Münsteraner Tierschutzvereins",
        "Beitragsart": "Textbeitrag",
        "Umfang": "31 S.",
        "Arbeitsbericht": "2 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 6",
        "Schule": "Schillergymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "594B52518CF9DC6A597F275C7BC28E",
        "Tutor*innenbericht": "",
        "Regest": "Die Schülerin verdeutlicht anhand des Tierschutzvereins Münster die Entwicklung des Tierschutzes. Ausgehend von Entwicklungen in England zu Beginn des 19. Jahrhunderts, wurde in Berlin 1840 der erste Tierschutzverein Deutschlands gegründet. 1845 wurde auch in Münster ein solcher Verein gegründet, der an den Berliner Verein angegliedert war, sich jedoch bald wieder auflöste. Erst 1927 wurde erneut ein Tierschutzverein von dem Ehepaar Maria und Heinrich Braun gegründet. Ihnen war insbesondere am Schutz der Droschkenpferde gelegen. Schnell zählte der Verein viele Mitglieder und konnte nachdem 1933 erste Gesetze gegen Tierquälerei erlassen wurden, auch auf gesetzliche Grundlagen zurückgreifen. Die Verfasserin verdeutlicht zudem die Probleme des Vereins, ausreichende finanzielle Unterstützung zu erhalten. Mitschriften der Zeitzeug*inneninterviews werden von ihr ausführlich dokumentiert. ",
        "Themenzeitraum von": 1840,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Archivalien|Druckschriften|Fachliteratur|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 297",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Mensing, Nele|Rolfes, Teresa",
        "Titel": "Turnier der Sieger",
        "Beitragsart": "Textbeitrag",
        "Umfang": "21 S.",
        "Arbeitsbericht": "1 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 7",
        "Schule": "Wilhelm-Hittorf-Gymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Gruppenbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "145EB2EAD9B0949A417A08B6055824",
        "Tutor*innenbericht": "",
        "Regest": "Die Schülerinnen beschäftigen sich mit dem „Turnier der Sieger“, einem großen jährlich stattfindenden Reitturnier in Münster. Es wurde das erste Mal 1955 vom Westfälischen Reiterverein organisiert. Nach einem kurzen Überblick über die Vereinsgeschichte und seine Aktivitäten, beschreiben die Schülerinnen die Entstehung des Turniers und seine Entwicklung seit 1955. Dieses wurde nach und nach zu einer immer größeren Veranstaltung und findet mittlerweile auf dem Schlossplatz mit dem Schloss Münsters als Kulisse statt. Jährlich zieht es bis zu 20.000 Besucher an.  ",
        "Themenzeitraum von": 1955,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Fachliteratur|Zeitungsartikel|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 311",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "Schlossplatz",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Naunin, Dörte",
        "Titel": "Münsters Zoo zieht um (1967-1974)",
        "Beitragsart": "Textbeitrag",
        "Umfang": "36 S.",
        "Arbeitsbericht": "2 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 10",
        "Schule": "Schillergymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "594B52518CF9DC6A597F275C7BC28E",
        "Tutor*innenbericht": "",
        "Regest": "Nach einem kurzen Abriss der Geschichte des 1871 gegründeten Münsterschen Zoos konzentriert sich die Verfasserin in ihrem Beitrag auf den Umzug des Zoos auf sein heutiges Gelände. Der damalige „Zoologische Garten“ musste umziehen, da die Stadt der Landesbausparkasse das Grundstück angeboten hatte. Das neue Zoogelände wurde von Beginn an für jede Wetterlage geplant, so dass er in „Allwetterzoo“ umbenannt wurde. Die Schülerin beschreibt den langwierigen Umzug der Tiere ab dem Jahre 1967, der bis 1973 dauerte und nicht ohne Probleme war, da man diesen möglichst schonend gestalten wollte. Anfang der 1970er Jahre startete der Zoo eine Spendenaktion, um für das größere Zoogelände neue Tiere anschaffen zu können. Weiterhin geht sie auf die Eröffnungsfeierlichkeiten, die teilweise Kritik an der Gestaltung der Gehege und den großen Erfolg des Zoos nach seiner Neueröffnung ein. ",
        "Themenzeitraum von": 1967,
        "Themenzeitraum bis": 1974,
        "Materialgrundlage": "Archivalien|Fachliteratur|Zeitungsartikel|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 290",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "Zoo",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Naunin, Swantje",
        "Titel": "Vogeljäger, Vogelsammler und Erholungssuchende in den Rieselfeldern Münster",
        "Beitragsart": "Textbeitrag",
        "Umfang": "123 S.",
        "Arbeitsbericht": "8 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 12",
        "Schule": "Schillergymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "594B52518CF9DC6A597F275C7BC28E",
        "Tutor*innenbericht": "",
        "Regest": "Der Beitrag beschäftigt sich mit den Veränderungen im Umgang mit den Tieren, insbesondere den Vögeln, im Feuchtbiotop der Münsteraner Rieselfelder während des 20. Jahrhunderts. Diese Rieselfelder dienten seit Ende des 19. Jahrhunderts der Verrieselung und damit Reinigung städtischer Abwässer. In dem Beitrag werden zahlreiche Primär- und Sekundärquellen aus der Arbeit der Natur- und Vogelschutzverbände zusammengestellt, und in 35 Gliederungspunkten werden die einzelnen Nutzungsinteressen der Landwirte, Jäger, Vogelschützer sowie weitere Einzelaspekte abgehandelt. In ihrem Zusammenspiel unterlagen deren Interessen einer historischen Wandlung, ebenso wie in ihrer jeweiligen Mensch-Tier-Beziehung. Die Schülerin beschreibt die Anlage und Nutzung der Rieselfelder, die ein bemerkenswertes Biotop entstehen ließen. Die Mensch-Tier-Beziehung bei diesem Thema ergab sich daraus, dass sich auf den nährstoffreichen Rieselfeldern zahlreiche Tiere und ihre menschlichen Jäger einfanden. Vor der Verbreitung der Kunstdünger versprachen diese Flächen zudem höhere landwirtschaftliche Erträge und wurden daher verpachtet. Neben der landwirtschaftlichen Nutzung erfolgte aber auch eine Verpachtung von Jagden. Die Bejagung war zeitweise so intensiv, dass z.B. das Kaninchen dort verschwand. Bereits 1935 wurden Randbereiche der Rieselfelder unter Naturschutz gestellt und Vogelbeobachtungsposten errichtet. Im diesem Kontext weist die Verf. auf die seit 1888 bestehenden Vogelschutzaktivitäten hin. Erst im Zuge der Mechanisierung der Abwasserklärung und hygienischer Einwände ging die landwirtschaftliche Nutzung der Rieselflächen zurück („Klärwerk statt Kloake“, S. 39 ff.). In den 70er Jahren wurde die Berieselung eingestellt, und das Feuchtbiotop dominiert seitdem das Gelände. Bereits in den 60er Jahren wurde das Areal regelmäßig besuchtes Exkursionsziel von ortsansässigen Vogelkundlern, heute leitet sich die überregionale Bedeutung insbesondere aus dem Charakter als Vogelrastplatz ab. Nach einer mehr als 100 S. umfassenden, teils sehr ins Detail gehenden Darstellung der gegensätzlichen Nutzungspraxis folgt eine Beschreibung der Entwicklung des Mensch-Tier-Verhältnisses in der Zusammenfassung („Vogelfrei? - Das Fazit“, S. 111 ff.): „Die Jäger in den Rieselfeldern in der Zeit zwischen 1900 und 1940 waren von einem globalen Ökologieverständnis weit entfernt, [...] Tiere waren Sachen.“ (S. 112). Die Gestaltung der Rieselfelder hat aber sicherlich zum Erhalt vieler, damals nicht geschützter Vogelarten beigetragen, schätzt die Verf. die Bedeutung des Areals ein. In vielen Naturschutzgebieten sei dies heute nicht mehr möglich, da diese zumeist zu kleinräumig sind. Obwohl die Tiere heute durch eine Reihe von Gesetzen geschützt und durch Schutzmaßnahmen in ihrem Bestand gefördert werden, haben sich ihre Lebensbedingungen außerhalb der Schutzareale stets verschlechtert, meint die Autorin. Auch wenn die Abbildungen und zahlreichen Fotos vom Gelände überwiegend illustrativ verwendet werden, so prägen sie die Arbeit doch sehr. Vor allem die Arbeit der Natur- und Vogelschutzverbände wird hiermit gut dargestellt.",
        "Themenzeitraum von": 1900,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Archivalien|Expert*inneninterviews|Druckschriften|Fachliteratur|Internetquellen|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 283",
        "Auszeichnungen": "4. Bundespreis",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "Rieselfelder",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "",
        "Titel": "",
        "Beitragsart": "",
        "Umfang": "",
        "Arbeitsbericht": "",
        "Jahrgangsstufe": "",
        "Schule": "",
        "Einzelbeitrag oder Gruppenbeitrag": "",
        "Schulart": "",
        "Tutor*in (ID)": "",
        "Tutor*innenbericht": "",
        "Regest": "",
        "Themenzeitraum von": null,
        "Themenzeitraum bis": null,
        "Materialgrundlage": "",
        "Signatur im Stadtarchiv": "",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": ""
      },
      {
        "Autor*in": "Ommer, Verena",
        "Titel": " „Tierisch“ viele Knochen aus Münsters Untergrund…ausgegrabene Tierknochen verschaffen uns Einblick in die Geschichte von Mensch und Tier",
        "Beitragsart": "Textbeitrag",
        "Umfang": "72 S.",
        "Arbeitsbericht": "2 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 7",
        "Schule": "Wilhelm-Hittorf-Gymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "145EB2EAD9B0949A417A08B6055824",
        "Tutor*innenbericht": "",
        "Regest": "Ausgangspunkt dieses Beitrags ist eine innerstädtische Ausgrabung in der Münsteraner Lotharingerstraße, bei der die Verf. mitmachen konnte. Durch den spezifischen Quellenzugang angeregt, fragt die Verf. nach dem räumlichen Zusammenleben von Mensch und Tier in der Vergangenheit. Der Ansatz ihres Beitrags zum Leben in der mittelalterlichen und frühneuzeitlichen Stadt besteht darin, ausgehend von archäologischen Funden mithilfe der Sekundärliteratur eine themenbezogene Darstellung zu entwickeln. Ausgehend von den Ausgrabungen fragt die Sch. nach dem Wert der Tiere in der spätmittelalterlichen und frühneuzeitlichen städtischen Gesellschaft. Sie vergleicht diesen mit den heutigen Wertsetzungen in der modernen Tierhaltung und Landwirtschaft. Der historische Wert wird, ausgehend von den Quellen, anschaulich beschrieben und die große Nähe sowie die Abhängigkeit des Menschen von seinen Tieren nachvollzogen. Im 3. Kapitel (\"Die Knochenfunde und ihre Auswertung\") werden die Erkenntnisse in einer von der Verf. gewerteten Rangfolge nach der Wichtigkeit von Tieren für den Menschen in der mittelalterlichen Stadt zusammengestellt. Die historische und grabungstechnische Beschreibung des Areals, auf dem sich zuvor Erbhöfe, ein Kloster, eine Kaserne und später ein Bunker befanden, nimmt im 4. Kapitel breiten Raum ein. Im 5. Kapitel geht die Verf. dem damaligen Aussehen, der Nahrung und Haltung, der Nutzung und Leistung sowie der Verwertung von Rind, Schwein, Schaf, Ziege, Huhn und anderem Federvieh nach. Die Frage, ob die Menschen im Mittelalter die Tiere mehr geachtet haben als heute, kann die Verf. im 6. Kapitel zum Mensch-Tier-Verhältnis nicht abschließend klären. Sie arbeitet jedoch deutlich heraus, dass die Tiere damals eine höhere Bedeutung hatten als heute. Dem eingereichten Beitrag lagen 18 original Knochenfunde von Rind, Schwein, Schaf und Ziege, Huhn sowie von Muschelresten bei, die an das Westfälische Museum für Naturkunde zurückgingen.",
        "Themenzeitraum von": 1300,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Archivalien|Druckschriften|Fachliteratur|Privatdokumente|Zeitungsartikel|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 335",
        "Auszeichnungen": "4. Bundespreis",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Pötzel. Charlotte",
        "Titel": "Pferde als Transport- und Arbeitstiere in Münster",
        "Beitragsart": "Textbeitrag",
        "Umfang": "98 S.",
        "Arbeitsbericht": "3 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 10",
        "Schule": "Schillergymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "594B52518CF9DC6A597F275C7BC28E",
        "Tutor*innenbericht": "",
        "Regest": "In ihrer Arbeit befasst sich die Schülerin ausführlich mit der historischen Nutzung von Pferden als Transport- und Arbeitstiere in Münster. Noch 1733 wurde Pferdekraft genutzt, um Schiffe auf dem Münsteraner Kanal zu ziehen – eine Verkehrsader, die nicht nur in dieser Hinsicht auf Pferde angewiesen war, wie die Verfasserin aufzeigt. Schließlich stellt sie im Kapitel „Pferde im Stadtbild“ dar, wie relevant Pferde und Pferdefuhrwerke für die Infrastruktur der Stadt waren: Von der Verteilung der am Hafen ankommenden Güter, über die am Markt teilnehmenden Bauern, als Transportmittel städtischer Handwerks- und Fertigungsbetriebe, bis hin zum Städtebau. Noch bis in die Mitte des 20. Jahrhunderts hinein spielten Pferde im städtischen Speditionswesen eine wichtige Rolle, wie die Verfasserin anhand eines Zeitzeug*inneninterviews mit Karl-August Peters, Urenkel des Gründers eines bis heute, wenn auch mit LKW, tätigen Speditionsunternehmens, aufzeigt. Angesichts dieser hohen Einbindung in den Alltag kam den Pferden ein hoher Stellenwert zu – und wurde der Umgang mit ihnen auch im preußisch regierten Münster behördlich genauestens geregelt, wie eine Auseinandersetzung mit der Straßen-Polizei-Ordnung von 1878 darlegt. Abschließend setzt sich die Autorin mit den weiteren Berufen, die im Umfeld der Pferdenutzung von Relevanz waren, sowie des historischen Personentransports, für den Pferde im Alltagswissen bekannter sind und der seine Überlieferung im Reitsport gefunden hat, auseinander. ",
        "Themenzeitraum von": 1733,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Archivalien|Druckschriften|Fachliteratur|Internetquellen|Zeitungsartikel|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 325",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Plöger, Patrik",
        "Titel": "Die Kuh ist weg! Was wäre die deutsche Werbung ohne ihre Stars? Tiere, die Marketingreißer des letzten Jahrhunderts!",
        "Beitragsart": "Textbeitrag",
        "Umfang": "71 S.",
        "Arbeitsbericht": " ",
        "Jahrgangsstufe": "Jahrgangsstufe 12",
        "Schule": "Wilhelm-Hittorf-Gymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "BE856E8D9500CE157E8F3DC442D90D",
        "Tutor*innenbericht": "",
        "Regest": "In seinem Beitrag geht der Schüler auf Tiere in der Werbung während des 20. Jahrhunderts in Deutschland ein. Dabei erläutert er zunächst aus historischer Perspektive den Einsatz von Tieren in der Werbung: viele Tiere kenne man aus Fabeln mit charakteristischen Eigenschaften, was sich Werbemacher zu Nutze machen würden. Er stellt ausgewählte Werbebeispiele vor, u.a. den Fuchs der Versicherungsgesellschaft „Schwäbisch Hall“ oder den Bär der „Bären-Marke“-Milchprodukte. Auch auf den häufigen Einsatz von Hunden in der Werbung geht er ein. In Münster sei Werbung mit Tieren insbesondere im Zusammenhang mit dem Zoo von Bedeutung. In einem zweiten Teil diskutiert der Schüler, inwiefern Tiermarketing im Sinne des Tierschutzes gerechtfertigt sei und setzt sich mit Tierschutz-Debatten auseinander.",
        "Themenzeitraum von": 1900,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Fachliteratur|Zeitungsartikel",
        "Signatur im Stadtarchiv": "4 SAB 641",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Ratte, Johanna",
        "Titel": "Die Ratte. Vom ekeligen Stinkvieh zum kuscheligen Schmusetier",
        "Beitragsart": "Textbeitrag",
        "Umfang": "57 S.",
        "Arbeitsbericht": "2 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 7",
        "Schule": "Marienschule",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "14280225FCA68606E54AB22299FFD7",
        "Tutor*innenbericht": "",
        "Regest": "Mit einem Nachnamen wie „Ratte“ - dies nutzt die Schülerin auch mit einem schmunzelnden Unterton aus - zieht man durchaus die Aufmerksamkeit auf sich. Nahe liegend, dass sie sich daher der Beziehung zwischen den Menschen und der Tierart Ratte in ihrem Beitrag zuwendet und in ihrer Dokumentation über den Wandel der Ratte vom „ekeligen Stinkvieh“ zum „kuscheligen Schmusetier“ berichtet. Um den Bedeutungswandel der Ratte zu erfassen, hat die Verf. eine Reihe von Experten befragt (die Protokolle sind unkommentiert im Anhang wiedergegeben). Zumeist bezieht sich die Verf. in ihrer Darstellung aber auf die Literatur. Ohne eine formulierte Fragestellung geht die Verf. in ihrer Recherche von ihrer Familiengeschichte aus und wendet sich im Verlauf der Arbeit insbesondere der Geschichte der Rattenbekämpfung zu (6 S.). Den Stammbaum (Anlage 1) ihrer Familie kann die Schülerin bis auf ihren Ahnen Johannes Ratte (geb. 1605) zurückverfolgen. Sie stellt dabei einen Zusammenhang zwischen der Namensgebung und den sieben Pestwellen im 16. und 17. Jahrhundert in dessen sauerländischer Heimat her. Im Anschluss an die Biologie der Ratte beschreibt die Verf. die verschiedenen „Verwendungen“ und Bedeutungszuweisungen der Ratte und deren Veränderungen. Auf die Gründe für die ablehnende Haltung gegenüber Ratten als Kulturfolger wird sie für die Verbreitung von Krankheiten verantwortlich gemacht, die anhaltenden Probleme bei der Bekämpfung von Ratten und die Haltung von Ratten als Versuchs- und Haustiere wird anschließend eingegangen. Historische Hintergründe werden insbesondere im Zusammenhang mit der Pest im Münsterländischen eingearbeitet. Mit ihrer „Schlussbetrachtung“ (S. 24 ff.) geht sie auf das Mensch-Tier-Verhältnis in ihrem speziellen Fall ein und beschreibt in „Mein Verhältnis zu meinem Namen“:  „Inzwischen bin ich fast stolz, den Namen eines so klugen und intelligenten Tieres führen zu können.“",
        "Themenzeitraum von": 1400,
        "Themenzeitraum bis": 1999,
        "Materialgrundlage": "Archivalien|Expert*inneninterviews|Fachliteratur|Internetquellen|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 315",
        "Auszeichnungen": "5. Bundespreis",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Reimer, Olga",
        "Titel": " „Heute gibt es keine Maika mehr!“ Unser Leben mit Tieren in Russland früher und ohne Tiere in Deutschland heute",
        "Beitragsart": "Textbeitrag",
        "Umfang": "24 S.",
        "Arbeitsbericht": "1 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 7",
        "Schule": "Wilhelm-Hittorf-Gymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "145EB2EAD9B0949A417A08B6055824",
        "Tutor*innenbericht": "",
        "Regest": "Die Schülerin stammt aus dem kleinen Dorf Kusak an der Grenze zu Kasachstan im Bereich der Kulunda-Steppe. In einem biographischen Zugriff beschreibt sie ihr Leben auf der Kolchose „Engels“ in Kusak und das enge Zusammenleben mit den dortigen Tieren, u.a. Kühe, Schweine, Hühner und Hunde. Insbesondere zu der Kuh „Maika“ hatte die Schülerin ein enges Verhältnis. Sie beschreibt, wie die Kolchose bewirtschaftet wurde und die Nutzung der Tiere, die der Familie durch die Herstellung von Nahrungsmitteln das Überleben sicherte. Als die Familie 1998 nach Deutschland übersiedelte, verkaufte sie ihr Haus und lebte fortan ohne Tiere.",
        "Themenzeitraum von": 1988,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Privatdokumente|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 288",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Rottwinkel, Malena|Schulte Blasum, Britta",
        "Titel": "Der Otto-Hahn-Park. Ein Mann und seine Leidenschaft: Tiere",
        "Beitragsart": "Textbeitrag",
        "Umfang": "52 S.",
        "Arbeitsbericht": "3 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 7",
        "Schule": "Marienschule",
        "Einzelbeitrag oder Gruppenbeitrag": "Gruppenbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "B0D1A952C83F620E206C2FD888C830",
        "Tutor*innenbericht": "",
        "Regest": "Von 1977 bis 1994 existierte auf dem Gelände der Universität Münster der Otto-Hahn-Park, eine Anlage mit über 250 seltenen Tieren. Dieser wurde von dem Mitarbeiter der Kfz-Stelle der Universität Friedrich Bock in Eigenregie aufgebaut und gepflegt. Bis 1975 war das 10.000 m² große Gelände eine Abfalldeponie, als diese jedoch geschlossen wurde, schlug Friedrich Bock vor, auf eigene Kosten einen Park mit Tierhaltung anzulegen. Diesen benannte er nach dem Physiker Otto Hahn. 1992 musste der Park geschlossen werden, da Geld für eine Renovierung fehlte, zudem setzte die Universität Friedrich Bock zusehends unter Druck. Daraufhin protestierten viele Bürger gegen die Schließung, so dass Bock 1993 einen Neuanfang wagte. Laut Aussage Bocks kam es 1994 zum vollständigen Bruch mit dem Kanzler der Uni, er wurde gekündigt und musste seinen Park aufgeben. ",
        "Themenzeitraum von": 1977,
        "Themenzeitraum bis": 1994,
        "Materialgrundlage": "Fachliteratur|Zeitungsartikel|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 293",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "Westfälische Wilhelms-Universität",
        "Personenregister": "Bock, Friedrich|Hahn, Otto",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Ruwe, Kathrin|Vielhauer, Dominique|Winter, Christina",
        "Titel": "Der letzte Wolf in Westfalen",
        "Beitragsart": "Textbeitrag",
        "Umfang": "28 S.",
        "Arbeitsbericht": "1 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 6",
        "Schule": "Kardinal-von-Galen-Gymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Gruppenbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "077B410CF952FDE588ED7660C9BA70",
        "Tutor*innenbericht": "",
        "Regest": "Der Beitrag behandelt die Beziehung zwischen Mensch und Wolf und die Geschichte des angeblich „letzten Wolfs in Westfalen“, der 1835 in Herbern bei Lüdinghausen von Joseph Hennemann erlegt wurde. Dieser Wolf wurde präpariert und im Naturkundemuseum Münster ausgestellt. Dort wo sich das Haus Hennemanns befand, ist heute eine Gaststätte, die mit ihrem Namen „Zum letzten Wolf“ an die Geschichte erinnert. Neben dem Gasthaus befindet sich auch ein Denkmal für den erlegten Wolf. Die Schülerinnen beschreiben die langsame Ausrottung des Wolfs durch den Menschen in ganz Deutschland und das schlechte Bild des Tieres in der Bevölkerung. Im Osnabrücker Zoo, der Wölfe hält, haben die Schülerinnen Zoobesucher zu ihrem Bild des Wolfs befragt. ",
        "Themenzeitraum von": 1835,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Expert*inneninterviews|Fachliteratur|Internetquellen|Umfragen|Zeitungsartikel",
        "Signatur im Stadtarchiv": "4 SAB 292",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "Lüdinghausen",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Schüling, Lukas",
        "Titel": "Vom Dämon zum geschützten Tier",
        "Beitragsart": "Textbeitrag",
        "Umfang": "27 S.",
        "Arbeitsbericht": "1 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 5",
        "Schule": "Schillergymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "594B52518CF9DC6A597F275C7BC28E",
        "Tutor*innenbericht": "",
        "Regest": "Der eher biologisch ausgerichtete Beitrag beschäftigt sich mit der Fledermaus als ein Tier, über das es viele Vorurteile gibt. Der Schüler beschreibt zunächst die Fledermaus im Allgemeinen und Fledermausarten. Dann nennt er verschiedene Sagen bzw. Volksweisheiten über die Fledermaus, z.B. wird sie häufig als Vorbote des Todes gedeutet, manchmal aber auch als Glückssymbol. Der Schüler hat auch ein Interview mit einem Fledermausschützer vom Naturschutzverband Münster geführt und dokumentiert dieses in seiner Arbeit.",
        "Themenzeitraum von": 2001,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Expert*inneninterviews|Fachliteratur",
        "Signatur im Stadtarchiv": "4 SAB 301",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Scherbel, Teresa|Schmalzried, Bettina",
        "Titel": "Schweine saustark",
        "Beitragsart": "Textbeitrag",
        "Umfang": "11 S.",
        "Arbeitsbericht": "1 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 5",
        "Schule": "Marienschule",
        "Tutor*innenbericht": "",
        "Regest": "In knapper Form behandeln die Schülerinnen verschiedene Aspekte zum Thema „Schwein“. Sie gehen auf Bauernhöfe, Fleisch als Lebensmittel und das Schlachten ein. Für ihren Beitrag haben sie eine Bäuerin befragt und auf dem Bauernhof einige Fotos geschossen.",
        "Themenzeitraum von": 1900,
        "Themenzeitraum bis": 1999,
        "Materialgrundlage": "Fachliteratur|Zeitungsartikel|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 309",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Schmidt, Saskia",
        "Titel": "Wale. Bericht über die Arbeit von Greenpeace für den Schutz der Wale",
        "Beitragsart": "Textbeitrag",
        "Umfang": "76 S.",
        "Arbeitsbericht": "1 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 5",
        "Schule": "Marienschule",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "B0D1A952C83F620E206C2FD888C830",
        "Tutor*innenbericht": "",
        "Regest": "In ihrem Beitrag zu Walen und der Arbeit von Greenpeace stellt die Schülerin Materialien zu ihrem Thema zusammen. Sie integriert vor allem Kopien aus Fachliteratur und Zeitschriften sowie online gefundene Informationen in ihre sehr knapp ausfallende Darstellung. Die Schülerin hat zwei Zeitzeug*inneninterviews mit Mitgliedern von Greenpeace geführt und dokumentiert diese in der Arbeit. ",
        "Themenzeitraum von": 1900,
        "Themenzeitraum bis": 1999,
        "Materialgrundlage": "Fachliteratur|Druckschriften|Internetquellen|Zeitungsartikel|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 312",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "Greenpeace",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Kortzfleisch, Vanessa von",
        "Titel": "Die Geschichte des Aquariums im Zoo von Münster",
        "Beitragsart": "Textbeitrag",
        "Umfang": "21 S.",
        "Arbeitsbericht": "1 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 6",
        "Schule": "Schillergymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "594B52518CF9DC6A597F275C7BC28E",
        "Tutor*innenbericht": "",
        "Regest": "Der erste Gehversuch eines Aquariums in Münster verlief 1885 im Sande. Erst mit neuerer Technologie konnte 1964 im Tropenhaus des zoologischen Gartens Münster ein Aquarium errichtet werden. Das ohnehin attraktiv und innovativ erscheinende Tropenhaus war so um eine Attraktion reicher, die die Autorin in ihrer Arbeit mittels zeitgenössischer Reaktionen in Zeitungsartikeln rekonstruiert. Auch mit dem Umzug des Zoos und der Neuerrichtung des Allwetterzoos wurde das Aquarium als integraler Bestandteil beibehalten. Auch dieses genoss ein hohes Maß an Popularität und Attraktivität – nicht zuletzt aufgrund von Zuchterfolgen und der Kooperation mit der Münsteraner Universität, vor allem aber dank der guten Zugänglichkeit und Anschaulichkeit, die auch die Autorin nach eigenen Angaben fasziniert. ",
        "Themenzeitraum von": 1964,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Archivalien|Fachliteratur|Zeitungsartikel|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 327",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "Zoo",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Warnecke, Antonia|Wiesker, Patricia",
        "Titel": "1643-1648. Tiere in Münster zur Zeit des Westfälischen Friedens ",
        "Beitragsart": "Textbeitrag|Bilderbuch",
        "Umfang": "51 S.|28 S.",
        "Arbeitsbericht": "3 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 7",
        "Schule": "Marienschule",
        "Einzelbeitrag oder Gruppenbeitrag": "Gruppenbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "FC97EEF30DCA26FF770C4AE5D0F506",
        "Tutor*innenbericht": "",
        "Regest": "In der vorliegenden Arbeit illustrieren die Autorinnen in Form eines Bilderbuches, welche Rolle Tiere in der Alltags- aber auch Symbolwelt Münsters zur Zeit des Westfälischen Friedens bzw. bereits während des 30-jährigen Kriegs spielten. Sich immer wieder mit aneinandergereihten allgemeinen Rahmeninformationen zu Kriegsausbruch, -verlauf und -ende abwechselnd, streuen die Verfasserinnen beispielsweise Informationen zur Nutzung von Pferden im Alltag oder der geläufigen, auch in diesem Kontext verwendeten, Friedenssymbolik der Taube ein. Auch das Bilderbuch ist ähnlich gehalten: Zeichnungen wechseln sich mit Hintergrundinformationen auf der Rückseite ab. ",
        "Themenzeitraum von": 1618,
        "Themenzeitraum bis": 1648,
        "Materialgrundlage": "Druckschriften|Fachliteratur|Internetquellen|Zeitungsartikel",
        "Signatur im Stadtarchiv": "4 SAB 334",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "Wiermer, Kathrin",
        "Titel": "Kleiner Wurm mit großer Wirkung im Wandel der Zeit. Oder: Wie der Altenberger Apotheker Engelsing zu seiner Blutegelzucht kam",
        "Beitragsart": "Textbeitrag",
        "Umfang": "128 S.",
        "Arbeitsbericht": "8 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 12",
        "Schule": "Marienschule",
        "Einzelbeitrag oder Gruppenbeitrag": "Einzelbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "FC97EEF30DCA26FF770C4AE5D0F506",
        "Tutor*innenbericht": "",
        "Regest": "Der Beitrag geht der Blutegelzucht in Altenberge, einem Ort nordwestlich von Münster, von 1865 bis 1917 nach und befasst sich mit der Bedeutung dieses therapeutischen Hilfsmittels in der Medizin. Der lokale Bezug wird über einen Apotheker in Altenberge hergestellt, der Blutegel züchtete und die Anwendung popularisierte. Bei der umfassenden Literaturrecherche stehen die medizinischen Aspekte im Vordergrund, zumal der regionalgeschichtliche Hintergrund kaum eine Verbindung mit der Biografie des Apothekers eingeht. „Die Geschichte der Blutegel-Therapie“ sowie der Handel mit Blutegeln steht am Beginn des Darstellungsteils (S. 12-27). Im Abschnitt über „Die Blutegelzucht in Altenberge“ (S. 28-56) nimmt die Biografie des Apothekers den dominierenden Teil ein. Die Wirkungsweise und therapeutischen Erfolge werden in „Geschichten rund um den Blutegel“ (S. 57-61) ohne den lokalen Fokus zusammengetragen. In der modernen (Schul-)Medizin hatten bis zur Renaissance der Biomedizin und der Homöopathie die Egel an Bedeutung verloren. Hygieneaspekte und die Verbreitung pharmazeutisch-industrieller Fabrikate drängten den Egel zurück, erklärt der Verfasserin. „Der medizinische Blutegel heute“ (S. 62-75) geht auf diese Renaissance ein und stellt auch die Verwendung von Egeln beim so genannten „Biocomputer“ vor. In dem Abschnitt „Abschließende Betrachtung“ (S. 76 ff.) geht die Verfasserin der Frage nach, ob die Blutegeltherapie nur eine Modeerscheinung war bzw. ist und verfolgt die Grenzen der wissenschaftlich-medizinischen Erklärungskraft. Da es zwischen Blutegeln und Menschen keine Kommunikation gibt, kann der Autor das Verhältnis zueinander nur als reines Nutzverhältnis beschreiben.* Der umfangreiche Anhang enthält eine Vielzahl der für die Arbeit genutzten archivalischen Quellen. ",
        "Themenzeitraum von": 1865,
        "Themenzeitraum bis": 2001,
        "Materialgrundlage": "Archivalien|Druckschriften|Fachliteratur|Internetquellen|Privatdokumente|Zeitungsartikel",
        "Signatur im Stadtarchiv": "4 SAB 295",
        "Auszeichnungen": "5. Bundespreis",
        "Wettbewerbsjahrgang": "2000-2001",
        "Ortsregister": "Altenberge",
        "Personenregister": "",
        "Wettbewerbskurztitel": "Genutzt - geliebt - getötet. Tiere in unserer Geschichte"
      },
      {
        "Autor*in": "",
        "Titel": "",
        "Beitragsart": "",
        "Umfang": "",
        "Arbeitsbericht": "",
        "Jahrgangsstufe": "",
        "Schule": "",
        "Einzelbeitrag oder Gruppenbeitrag": "",
        "Schulart": "",
        "Tutor*in (ID)": "",
        "Tutor*innenbericht": "",
        "Regest": "",
        "Themenzeitraum von": null,
        "Themenzeitraum bis": null,
        "Materialgrundlage": "",
        "Signatur im Stadtarchiv": "",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": ""
      },
      {
        "Autor*in": "Brüggemann, Lea|Hippen, Sophia",
        "Titel": "Lämmer Gottes?",
        "Beitragsart": "Textbeitrag",
        "Umfang": "44 S.",
        "Arbeitsbericht": "4 S.",
        "Jahrgangsstufe": "Jahrgangsstufe 8",
        "Schule": "Kardinal-von-Galen-Gymnasium",
        "Einzelbeitrag oder Gruppenbeitrag": "Gruppenbeitrag",
        "Schulart": "Gymnasium",
        "Tutor*in (ID)": "7A4E717D0A1A134EF5711A14906A72",
        "Tutor*innenbericht": "",
        "Regest": "Dem Ministranten-Amt wird in der katholischen Liturgie besondere Bedeutung beigemessen: In ihrer Tätigkeit als Messdienerinnen und Messdiener am Altar stehen sie seit dem 9. Jahrhundert als Repräsentanten der Gemeinde dem Priester gegenüber. Dabei sind diese Repräsentantinnen und Repräsentanten meist selbst noch Jugendliche im Alter zwischen 12 und 18 Jahren. Die Verfasserinnen dieser Arbeit, selbst Ministrantinnen, beleuchten daher ein Amt, das zwischen den Generationen vermitteln soll, genauer. Zugleich finden sich in den Ministranten-Gruppen-Stunden häufig die Jugendlichen einer Gemeinde zusammen. Historisch betrachtet stellen die Autorinnen fest, dass es den deutlichsten Einschnitt in den 1970er-Jahren gegeben hat, als erstmals auch Mädchen für das Domministrantinnen-Amt in Münster zugelassen wurden. Die Geschlechterfrage erscheint ihnen in der katholischen Kirche und Liturgie immer noch als relevant.",
        "Themenzeitraum von": 813,
        "Themenzeitraum bis": 2007,
        "Materialgrundlage": "Fachliteratur|Internetquellen|Privatdokumente|Zeitzeug*inneninterviews",
        "Signatur im Stadtarchiv": "4 SAB 574",
        "Auszeichnungen": "",
        "Wettbewerbsjahrgang": "2006-2007",
        "Ortsregister": "",
        "Personenregister": "",
        "Wettbewerbskurztitel": "miteinander - gegeneinander? Jung und Alt in der Geschichte"
      }
    
     ]);
     
    return (


      <>
  <Navbar className="custom-nav" variant="light">
    <Navbar.Brand href="#home"><img className="booklogo" src={booklogo} style={{"width" : 50, "height" : 50}}/></Navbar.Brand>
    <Nav className="mr-auto">
      <Nav.Link href="#home">Start</Nav.Link>
      <Nav.Link href="#features">Dokumente</Nav.Link>
      <Nav.Link href="#pricing">Über uns</Nav.Link>
    </Nav>
    <Form inline>
      <FormControl type="text" placeholder="Suche" className="mr-sm-2" />
    </Form>
  </Navbar>
      <div className="site">

      <div  className="main-content-wrapper">
        <img className="logo" src={booklogo}/>
        <h1 className="title">geschichtswettbewerb.ms</h1>
        <div className="text-wrapper">
        <p>Der Geschichtswettbewerb des Bundespräsidenten ist der größte historische Forschungswettbewerb für junge Menschen in Deutschland. Seit 1973 sind rund 33.500 Beiträge vor allem von Schülerinnen und Schülern entstanden. Der Wettbewerb will bei Kindern und Jugendlichen unter 21 Jahren das Interesse für die eigene Geschichte wecken, selbständiges Lernen und Forschen fördern sowie gesellschaftliches Verantwortungsbewusstsein stärken. Ausgeschrieben wird der Geschichtswettbewerb zu wechselnden Themen in einem zweijährigen Turnus durch die Körber-Stiftung (www.koerber-stiftung.de/geschichtswettbewerb). Besonders gelungene Beiträge werden durch Landes- und Bundespreise prämiert.</p>
        <h1>Münsters besondere Leistungen</h1>
        <p>In keiner anderen Stadt haben seit 1973 so viele Kinder und Jugendliche am Geschichtswettbewerb des Bundespräsidenten teilgenommen wie in Münster. In den letzten knapp 50 Jahren entstanden an die 1700 Arbeiten, die historische Themen für die Stadtgeschichte auch neu erschlossen haben. Gemeinsam mit dem Stadtarchiv Münster hat das Institut der Didaktik der Geschichte an der Uni Münster diese Forschungsbeiträge vollständig erfasst. Diese Datensammlung enthält unter anderem Angaben zu Autoren, Inhalten, Ortsbezügen oder Auszeichnungen und ist bundesweit einzigartig. Während des Münsterhacks 2020 entstanden hieraus ein strukturiertes Datenmodell und darauf aufbauend eine Datenbankanwendung. Deren Nutzungsmöglichkeiten für die Geschichtslandschaft in Münster sind vielfältig: Sie ermöglicht Überblicke über Themen, untersuchte Orte oder Fragestellungen aller im Stadtarchiv analog gesammelten und einsehbaren Schülerbeiträge. Darüber hinaus kann sie Zusammenhänge zwischen den Beitragsformaten, Vorgehensweisen der Verfasserinnen und Verfasser und möglichen Auszeichnungen darstellen. Damit werden die Daten auch für die universitäre Forschung über Geschichte und schulisches Geschichtslernen interessant.</p>
        </div>

        <h1>Übersicht der Einreichungen<br/> aus Münster</h1>
        <div className="ag-theme-alpine">
            <AgGridReact className="myTable"
                rowData={rowData}>
                <AgGridColumn field="Autor*in" sortable={true} filter={true}></AgGridColumn>
                <AgGridColumn field="Titel" sortable={true} filter={true}></AgGridColumn>
                <AgGridColumn field="Beitragsart" sortable={true} filter={true}></AgGridColumn>
                <AgGridColumn field="Umfang"></AgGridColumn>
                <AgGridColumn field="Arbeitsbericht"></AgGridColumn>
                <AgGridColumn field="Jahrgangsstufe"></AgGridColumn>
                <AgGridColumn field="Schule"></AgGridColumn>
                <AgGridColumn field="Einzel/Gruppe"></AgGridColumn>
                <AgGridColumn field="Schulart"></AgGridColumn>
                <AgGridColumn field="Tutor"></AgGridColumn>
                <AgGridColumn field="Tutorbericht"></AgGridColumn>
                <AgGridColumn field="von"></AgGridColumn>
                <AgGridColumn field="bis"></AgGridColumn>
                <AgGridColumn field="Materialgrundlage"></AgGridColumn>
                <AgGridColumn field="Materialgrundlage"></AgGridColumn>
                <AgGridColumn field="Signatur"></AgGridColumn>
                <AgGridColumn field="Auszeichnung"></AgGridColumn>
                <AgGridColumn field="Wettbewerbsjahrgang"></AgGridColumn>
                <AgGridColumn field="Ortsregister"></AgGridColumn>
                <AgGridColumn field="Personenregister"></AgGridColumn>
                <AgGridColumn field="Wetbewerbskurztitel"></AgGridColumn>
            </AgGridReact>
          </div>
          <div className="map-container">
          <h1>Münster Karte</h1>
          <Map center={[51.9625101, 7.6251879]} zoom={12}>
      <TileLayer
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
      />

      {locationData.features.map(location => (
        <Marker key={location.properties.PARK_ID} position={[
          location.geometry.coordinates [0],
          location.geometry.coordinates [1]
        ]} />
      ))}
      </Map>
      </div>
        </div>
        </div>
        </>
    );
};

export default App;